<a href="https://colab.research.google.com/github/Tvamsiprakash/Bus-reservation-system/blob/main/Reshape_and_random_number_generation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy

In [18]:
import numpy as np
np.random.random()

0.21314910132749076

In [25]:
np.random.random((3,3))


array([[0.58085248, 0.76749092, 0.28611311],
       [0.00707205, 0.85975552, 0.65293182],
       [0.72684991, 0.93842206, 0.33530611]])

In [24]:
np.arrange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [23]:
np.linspace(1,30,25)

array([ 1.        ,  2.20833333,  3.41666667,  4.625     ,  5.83333333,
        7.04166667,  8.25      ,  9.45833333, 10.66666667, 11.875     ,
       13.08333333, 14.29166667, 15.5       , 16.70833333, 17.91666667,
       19.125     , 20.33333333, 21.54166667, 22.75      , 23.95833333,
       25.16666667, 26.375     , 27.58333333, 28.79166667, 30.        ])

In [31]:
arr1 = np.random.random((3,5))
arr1.reshape((5,3))
arr1.flatten()

array([0.99976819, 0.99328169, 0.60502343, 0.80252647, 0.26803312,
       0.44997632, 0.12663625, 0.26807991, 0.96616534, 0.94250758,
       0.39192771, 0.75623403, 0.78065802, 0.22207267, 0.21862155])